### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by terminalqo** [Aaaaaaaty/react_movie#1]
![Markdown](http://i2.kiimg.com/1949/bdfb2036d0daf988.png)

**Comment by Aaaaaaaty** [comment]
@weishijun14 由于这个代码有些历史原因，在最开始的时候webpack是1.0版本，你的可能是2.x然后报错

**Comment by terminalqo** [comment]
@Aaaaaaaty 但是package.json里面装的是``` "webpack": "^1.14.0"```

**Comment by Aaaaaaaty** [comment]
@weishijun14 你这个图里面显示的是compile成功啊，错误点是哪里，以及你这个多了个[]导致图片没显示出来

**Comment by weishijun14** [comment]
@Aaaaaaaty 额。。图片搞定了。。webpack打包之后的dist里面只有index.html一个文件， 没有index.js 和 common.js文件

**Comment by Aaaaaaaty** [comment]
@weishijun14 你用的是webpack命令么 还是npm start？ npm start你可以看下命令 它走的是dev-server，打包出来的文件在内存中直接看应该看不见

**Comment by terminalqo** [comment]
@Aaaaaaaty 编译成功后直接浏览器打开吗？

**Comment by Aaaaaaaty** [comment]
@weishijun14 编译成功之后应该会起一个静态服务器 localhost:8080还是多少监听了一个端口 打开那个地址就可以

**Comment by terminalqo** [comment]
解决了。。为什么同一wifi下，在手机上用```http://192.168.1.126:8080```无法打开。。126是我ip

**Comment by Aaaaaaaty** [comment]
@weishijun14 dev-server 起的服务localhost是否能转到本地ip我还不太确定。如果你自己另起一个本地服务，然后使用webpack命令进行build打包放进去应该是可以打开的
