### ISSUE TITLE
按照步骤下载克隆后，npm start环节出错

### ISSUE THREAD

**Issue by MessierObject111** [Aaaaaaaty/react_movie#3]
你好，我尝试了一下在本地部署这个app，但是我遇到了一些问题：在按照步骤操作下载克隆，npm install, 复制data和image到dist，运行npm start，terminal报错如下：
CHONGYUs-MacBook-Pro:react-movie chongyuli$ npm start

> 1212@1.0.0 start /Users/chongyuli/Documents/GitHub/react-movie
> webpack-dev-server --devtool --inline --hot --progress --colors --content-base dist

clean-webpack-plugin: /Users/chongyuli/Documents/GitHub/react-movie/dist has been removed.
clean-webpack-plugin: 1 file(s) excluded - index.html
 70% 2/2 build modulesevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 1212@1.0.0 start: `webpack-dev-server --devtool --inline --hot --progress --colors --content-base dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 1212@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chongyuli/.npm/_logs/2018-04-13T09_28_50_107Z-debug.log

请问是我缺失了什么环节吗？多谢

**Comment by Aaaaaaaty** [comment]
@MessierObject111 webpack 全局安装的版本是多少？印象中我的webpack当时是1.x
